"""Emit docs/COLUMN_ASSIGNMENT_REVIEW_4290-1.md from the audit evidence files.

Narrative is authored here; every table is generated from
output/audit_4290_1/*.json / *.csv so the doc cannot drift from the data.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AUD = ROOT / "output" / "audit_4290_1"
DOC = ROOT / "docs" / "COLUMN_ASSIGNMENT_REVIEW_4290-1.md"

REF = "20260707_1358_.csv"

hdr = json.loads((AUD / "header_audit.json").read_text(encoding="utf-8"))
pqv = json.loads((AUD / "parquet_verification.json").read_text(encoding="utf-8"))
sem = json.loads((AUD / "semantic_checks.json").read_text(encoding="utf-8"))
slp = json.loads((AUD / "sleep_onehot_check.json").read_text(encoding="utf-8"))
tax = json.loads((AUD / "time_axis_check.json").read_text(encoding="utf-8"))
aln = json.loads((AUD / "mmx_alignment.json").read_text(encoding="utf-8"))
sc = json.loads((AUD / "sleep_and_comment.json").read_text(encoding="utf-8"))
tbl = pd.read_csv(AUD / "column_review_table.csv")
tbl.loc[tbl.common_name.isna(), "review_flag"] = "NO_ASSIGNMENT"

CSVS = list(pqv.keys())
ref = tbl[tbl.csv == REF].sort_values("csv_col_index")
by_ig = {int(r.i_group): r for r in ref.itertuples() if pd.notna(r.i_group)}


def md_table(rows: list[list], head: list[str]) -> str:
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


def fmt(v, n=4):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    if isinstance(v, float):
        return f"{v:.{n}g}"
    return str(v)


def esc(s) -> str:
    return str(s).replace("|", "\\|")


def simplify_mmx(n) -> str:
    """Collapse Persyst's nested boolean instrument names into readable shorthand."""
    if not isinstance(n, str):
        return ""
    n = re.sub(r"SumValues_Abs_0-0 \[Rhythmicity Spectrogram 3\.00 (\w+ \w+)_avg\]",
               r"deltaFreq(\1)", n)
    n = re.sub(r"SumValues_Abs_2-2 \[Rhythmicity Spectrogram 3\.00 (\w+ \w+)_avg\]",
               r"deltaPow(\1)", n)
    n = re.sub(r"EventDensity Spike (?:F3|Fp1)[^<]*<Detector,Count_epoch>", "SpikeLeft", n)
    n = re.sub(r"EventDensity Spike (?:F4|Fp2)[^<]*<Detector,Count_epoch>", "SpikeRight", n)
    n = re.sub(r"EventDensity SpikeGen <Detector,Count_epoch>01", "SpikeGen", n)
    return re.sub(r"\s+", " ", n).strip()


def ig(n: int):
    return by_ig.get(n)


L: list[str] = []
w = L.append

w("# Column-assignment review — patient 4290-1, limited research-trend CSVs")
w("")
w("Generated by `scripts/audit_4290_1_columns.py` + `scripts/gen_4290_1_review_doc.py`.")
w("Every number below is read out of the evidence files in `output/audit_4290_1/`;")
w("nothing in this document is hand-entered.")
w("")
w("**Scope.** The three CSVs exported with the limited research-trend panel. The")
w("2.4 GB full-research-panel export (`20260708_1400_.csv`) is deliberately **not**")
w("covered here — it draws on a different panel and needs its own pass.")
w("")
w("**Authority.** These exports were produced from the `Research-Trends` panel of")
w(f"`{Path(aln['mmx_path']).name}`. §3.4 establishes that link column-by-column, and")
w("the MMX definition — not a regex over the trend name — is treated as the ground")
w("truth for what every column *is* throughout this document.")
w("")
w("---")
w("")

# ── 1. Inputs ────────────────────────────────────────────────────────────
w("## 1. What was processed")
w("")
rows = []
for c in CSVS:
    h = hdr["per_file"][c]
    p = pqv[c]
    rows.append([
        f"`{c}`", f"{p['csv_bytes']/1e6:.1f} MB",
        f"`{Path(h['source_dat']).name}`",
        h["test_date"] + " " + h["test_time"],
        f"{p['parquet_rows']:,}",
        f"{p['clock']['duration_hours']:.20f} h",
        f"{p['parquet_columns']}",
    ])
w(md_table(rows, ["CSV", "Size", "Source .dat (from `File,` header row)",
                  "TestDate / TestTime", "Data rows", "Span", "Parquet cols"]))
w("")
w("Patient identity resolved from the `.dat` stem by `qeeg.ingestion.identity.derive_patient_id`:")
w(f"all three → `{hdr['per_file'][REF]['derived_patient_id']}`.")
w("")
w("Parquet written to the local cache (never the share):")
w("")
for c in CSVS:
    w(f"- `{c}` → `{pqv[c]['parquet_path']}` ({pqv[c]['parquet_bytes']/1e6:.1f} MB)")
w("")
w("---")
w("")

# ── 2. How assignment works ──────────────────────────────────────────────
w("## 2. How a column gets its identity")
w("")
w("A Persyst trend CSV carries the semantics in **two header rows**, not in the data.")
w(f"In these files the code row is CSV row index **{hdr['per_file'][REF]['code_row_index']}** "
  f"(0-based) and the trend-name row is index **{hdr['per_file'][REF]['trend_row_index']}**.")
w("")
w("```")
w("row 6 (trend names) : ,,\"aEEG, All 10-20\",,,,,\"aEEG, Left Hemisphere\",,,,, ...")
w("row 7 (I-codes)     : ClockDateTime,Time,I1_1,I1_2,I1_3,I1_4,I1_5,I2_1, ...")
w("row 8+              : data")
w("```")
w("")
w("The trend name appears **once** per instrument (merged-cell style) and is")
w("fill-forwarded across that instrument's sub-columns. So `I1_1 … I1_5` all inherit")
w("`aEEG, All 10-20`, and the *position* `_1 … _5` is what distinguishes them.")
w("")
w("`I{n}` is not an arbitrary label: **`n` is the instrument's ordinal position in the")
w("MMX panel that produced the export** (§3.4). The trend-name text is a *display*")
w("label composed by Persyst; the panel position is the identity.")
w("")
w("The pipeline's assignment path, in order:")
w("")
w("1. **`qeeg/ingestion/parser.py`** — locates the code row (first row containing")
w("   `ClockDateTime` where ≥half the non-empty cells match `I\\d+_\\d+`), fill-forwards")
w("   the trend row, and builds `code_to_description = {I-code → trend name}`.")
w("2. **`qeeg/ingestion/column_mapper.py::classify_family`** — regex-matches the trend")
w("   name against `FEATURE_FAMILIES` in `qeeg/constants.py`; first pattern wins.")
w("3. **`get_subcolumn_name`** — resolves the `_k` position to a name, trying in order:")
w("   (a) the family schema in `qeeg/ingestion/subcol_schema.py`,")
w("   (b) the legacy `I_GROUP_SUBCOLUMN_NAMES` table keyed by **I-group number**,")
w("   (c) trend-name parsing.")
w("4. **`generate_common_name`** — builds the export identifier from family + band +")
w("   hemisphere + region + electrode + sub-column name.")
w("")
w("`common_name` is the identifier that reaches exports and the multi-segment")
w("semantic merge. **It is the thing that has to be unique and correct.**")
w("")
w("There is also an MMX-aware path, `build_column_schema_with_mmx`, which is supposed")
w("to take family and channels from the MMX instead of regex. §3.4 shows it does not")
w("fire for these files, and why.")
w("")
w("The raw Parquet does *not* store `common_name` — see §5.")
w("")
w("---")
w("")

# ── 3. Structural verification ───────────────────────────────────────────
w("## 3. Structural verification")
w("")
w("### 3.1 The three files are structurally identical")
w("")
cross = hdr["cross_file"]
rows = [[f"`{c}`", cross[c][f"identical_to_{REF}"], cross[c]["n_columns"],
         cross[c]["first_difference"] or "none"] for c in cross]
w(md_table(rows, [f"CSV vs `{REF}`", "Identical (code, trend name) sequence",
                  "Columns", "First difference"]))
w("")
w("Same 293 I-codes (plus `Time`), same order, same trend names. Any assignment")
w("finding below applies verbatim to all three files — which is why the §7 table")
w("is printed once.")
w("")

w("### 3.2 Sub-column count contract")
w("")
w("`qeeg/ingestion/subcol_validator.py` checks each instrument's observed")
w("`max(sub-index)` against the expected count in `subcol_schema.py` "
  "(mirror of `PersystTrendCSV_Format_Reference.md` §3).")
w("")
rows = [[f"`{c}`", tax[c]["n_icode_columns"], hdr["per_file"][c]["n_instruments"] - 1,
         len(hdr["per_file"][c]["subcol_mismatches"])] for c in CSVS]
w(md_table(rows, ["CSV", "I-code columns", "Instruments", "Sub-col contract violations"]))
w("")
w("**Zero violations.** Every fixed-cardinality family has exactly the expected width:")
w("aEEG = 5, Artifact Intensity = 3, Artifact Detector = 18,")
w("Electrode Signal Quality = 22, and every single-value family = 1.")
w("")

w("### 3.3 Column inventory — one column has no assignment at all")
w("")
w("The code row is `ClockDateTime, Time, I1_1, I1_2, …`. `Time` is neither")
w(r"`ClockDateTime` nor an `I\d+_\d+` code, so:")
w("")
w("- the parser **keeps** it in `code_to_description` with an empty trend name")
w("  (the trend-name cell above it is blank), and it reaches the Parquet;")
w("- `build_column_schema` **skips** it, because its regex only matches I-codes.")
w("")
w("It therefore has no family, no `sub_column_name` and no `common_name` — it is the")
w("one column in the file with zero semantic assignment. Empirically it is a 0-based")
w("**row counter**, not a time value:")
w("")
rows = [[f"`{c}`", tax[c]["parquet_columns"], tax[c]["n_icode_columns"],
         ", ".join(f"`{x}`" for x in tax[c]["n_non_icode_named_columns"]),
         tax[c]["time_is_row_counter"]] for c in CSVS]
w(md_table(rows, ["CSV", "Parquet cols", "I-code cols",
                  "Non-I-code cols besides `ClockDateTime`", "`Time` == row index 0…n-1"]))
w("")
w("So 295 Parquet columns = 293 I-codes + `ClockDateTime` + `Time`. Note that")
w("`header_audit.json` reports `n_icode_columns: 294` — that count includes `Time`,")
w("because the parser's dict excludes only `ClockDateTime`.")
w("")
w("This is distinct from `I232_1`, whose *trend name* is also `Time` (§6.8).")
w("")

# 3.4 — MMX
w("### 3.4 MMX provenance — the `Research-Trends` panel is the export definition")
w("")
w(f"`{Path(aln['mmx_path']).name}` ({aln['mmx_bytes']:,} bytes) contains")
w(f"{aln['mmx_panel_count']} panel definitions. The panel named **`{aln['export_panel']}`** lists")
w(f"**{aln['exported_instruments']} instruments** in display order.")
w("")
w("Persyst then appends two pseudo-columns, `Comment` and `Time`, which have no MMX")
w("instrument. The export therefore carries two more I-groups than the panel has")
w("instruments:")
w("")
w(f"{aln['exported_instruments']} instruments + `Comment` + `Time` = "
  f"**{aln['exported_instruments'] + 2} I-groups** (`I1` … `I{aln['exported_instruments'] + 2}`).")
w("")
w("**Alignment test.** Pair the *k*-th panel instrument with `I{k}`. The assertion is")
w("that each CSV trend name begins with that instrument's display label — its")
w("`GraphTitle`, or its `Name` when `GraphTitle` is empty:")
w("")
rows = [[f"`{c}`", aln["per_file"][c]["csv_i_groups"], aln["exported_instruments"],
         aln["per_file"][c]["count_matches_panel"],
         aln["per_file"][c]["graph_title_prefix_mismatches"]] for c in CSVS]
w(md_table(rows, ["CSV", "CSV I-groups", "Panel instruments",
                  "Counts match (+2 tail)", "Label-prefix mismatches"]))
w("")
w("The test does not use the ordinal rule to check itself: it compares the CSV's own")
w("trend text against the MMX's own label text at each position. Agreement at every")
w("position is therefore independent evidence for the mapping.")
w("")
w(f"**{aln['exported_instruments']} of {aln['exported_instruments']}, zero mismatches, in all three files.** The mapping `I{{n}}` → MMX")
w("instrument is therefore established, not inferred. Full table in")
w("`output/audit_4290_1/mmx_instrument_map.csv`; first rows:")
w("")
imap = pd.read_csv(AUD / "mmx_instrument_map.csv")
rows = [[r.panel_pos, f"`{r.i_group}`", r.n_sub_columns, esc(r.csv_trend_name)[:42],
         f"`{esc(r.mmx_name)[:44]}`", "" if pd.isna(r.mmx_channels) else r.mmx_channels]
        for r in imap.head(8).itertuples()]
w(md_table(rows, ["Panel pos", "I-group", "Sub-cols", "CSV trend name",
                  "MMX instrument Name", "MMX Channels"]))
w("")
w("> **Why the pipeline's MMX path does not fire.** `build_column_schema_with_mmx`")
w("> looks the trend name up in `mmx.instruments`, which `mmx_parser.py` keys by the")
w("> instrument **`Name`** attribute. The CSV carries the composed **display label**")
w("> instead. Matching by `Name` hits 1 of 222 distinct trend names; matching by")
w("> `GraphTitle` alone hits 25. Neither is usable, so every file silently falls back")
w("> to the regex path and logs `MMX: unmatched trend name` 222 times. **The join key")
w("> is the panel position, not any name.** Until that is fixed the MMX cannot correct")
w("> the regex — which is why the §6 defects reach downstream consumers unchallenged.")
w("")
w("---")
w("")

# ── 4. Evidence ──────────────────────────────────────────────────────────
w("## 4. Independent evidence from the data itself")
w("")
w("§3.4 establishes what each column *should* be. This section confirms it from the")
w("data independently — internal-consistency properties that can only hold if the")
w("assignment is right. All run on the full Parquet, no sampling.")
w("")

w("### 4.1 aEEG sub-columns are (max, min, p50, p75, p25) — CONFIRMED")
w("")
w("`subcol_schema.AEEG` claims positions 1–5 are `max, min, p50, p75, p25`.")
w("If true, then for every row `min ≤ p25 ≤ p50 ≤ p75 ≤ max` must hold.")
w("")
rows = []
for c in CSVS:
    for lab in ("all", "left", "right", "anterior", "posterior"):
        rows.append([f"`{c}`", lab, f"{sem[c][f'aeeg_{lab}_order_ok_pct']}%",
                     sem[c][f"aeeg_{lab}_violations"]])
w(md_table(rows, ["CSV", "aEEG channel set", "Rows satisfying ordering", "Violations"]))
w("")
tot = sum(pqv[c]["parquet_rows"] for c in CSVS)
w(f"**0 violations in {tot:,} rows × 5 channel sets.** The percentile ordering is")
w("exact, so the position→statistic mapping is correct. (This also rules out the")
w("pre-2026-05-21 `upper_margin / lower_margin / bandwidth / percent_bs / amplitude`")
w("labelling, which would not produce a monotone ordering.)")
w("")

w("### 4.2 `Relative {band}, X/1-30 Hz` are relative band powers — CONFIRMED")
w("")
w("MMX says so directly — `I213` is `FFT_PowerRatio 1-4//1-30 All 10-20_avg`. The data")
w("agree: four fractions of the same 1–30 Hz total must sum to 1.")
w("")
rows = []
for c in CSVS:
    s = sem[c]
    rows.append([f"`{c}`", s["relpower_all_sum_median"], s["relpower_all_sum_min"],
                 s["relpower_all_sum_max"], f"{s['relpower_all_sum_within_1pct']}%"])
w(md_table(rows, ["CSV", "Median sum", "Min", "Max", "Rows within 1% of 1.0"]))
w("")
w("Sum = 1.000 (max never exceeds 1.000002). The residual rows are fully suppressed")
w("epochs where all four are 0. The pipeline classifies 27 of these 36 columns as")
w("`other` and the other 9 as `alpha_variability`. See §6.1 / §6.2.")
w("")

w("### 4.3 RAV and `Relative Alpha` are different signals — CONFIRMED")
w("")
w("MMX: `I94` = `FFT_PowerRatio 6-14//1-20 All 10-20_avg` (RAV);")
w("`I195` = `FFT_PowerRatio 8-13//1-30 All 10-20_avg` (relative alpha power).")
w("Different numerator *and* different denominator. The pipeline maps both onto the")
w("same `rav_*` names; the data confirm they are not the same series:")
w("")
rows = [[f"`{c}`", sem[c]["rav_I94_vs_relalpha_I195_identical"],
         sem[c]["rav_I94_vs_relalpha_I195_corr"],
         sem[c]["rav_I94_vs_relalpha_I195_max_absdiff"]] for c in CSVS]
w(md_table(rows, ["CSV", "`I94_1` == `I195_1`", "Pearson r", "Max abs. difference"]))
w("")
w("**Nine such pairs collide onto one name each.** See §6.2.")
w("")

w("### 4.4 SEF percentiles are ordered correctly — CONFIRMED")
w("")
w("SEF50 ≤ SEF75 ≤ SEF90 ≤ SEF95 must hold row-wise if the percentile numbers were")
w("parsed correctly.")
w("")
rows = [[f"`{c}`", f"{sem[c]['sef_monotonic_pct']}%", sem[c]["sef_violations"]] for c in CSVS]
w(md_table(rows, ["CSV", "Rows satisfying SEF50≤SEF75≤SEF90≤SEF95", "Violations"]))
w("")

w("### 4.5 Sleep block — MMX and data agree exactly")
w("")
w("`I146_1` and `I153_1` are identical categorical stage codes (0–5); `I147_1 … I152_1`")
w("are binary indicators. The MMX names each indicator with the stage code it tests,")
w("and the data independently show which code each indicator fires on. **They match")
w("one-for-one:**")
w("")
mapping = slp[REF]["indicator_to_I146_code"]
rows = []
for k, v in mapping.items():
    r = ig(int(k.split("_")[0][1:]))
    rows.append([f"`{k}`", f"`{esc(r.mmx_name) if r is not None else ''}`",
                 ", ".join(str(x) for x in v),
                 " / ".join(str(slp[c]["indicator_to_I146_code"][k]) for c in CSVS)])
w(md_table(rows, ["Indicator column", "MMX instrument Name",
                  "Stage code where indicator = 1 (observed)", "Same across all 3 CSVs"]))
w("")
rows = [[f"`{c}`", f"{slp[c]['onehot_sum_is_1_pct']}%", slp[c]["I146_equals_I153"]]
        for c in CSVS]
w(md_table(rows, ["CSV", "Rows where the six indicators sum to exactly 1",
                  "`I146_1` == `I153_1`"]))
w("")
w("`I146` is the `SleepStages` engine output; `I153` is a `ColorScaledBars` display")
w("instrument reading the same values. All seven columns currently share the single")
w("name `sleep_stage_display` — see §6.3.")
w("")
w("**What the stage codes mean — partially resolved from the MMX palettes.**")
w("The MMX defines two colour palettes over the same 0–5 code space:")
w("")
w("```")
for k, v in sc["palettes"].items():
    w(f"{k:<12} {','.join(v)}")
w("```")
w("")
w("`SleepWake` is the same six slots with codes 1–4 **collapsed to one colour**:")
w("")
w(md_table([[c, ", ".join(str(x) for x in codes)]
            for c, codes in sc["sleepwake_colour_groups"].items()],
           ["Colour", "Stage codes sharing it in `SleepWake`"]))
w("")
w("The `ColorScaledBars` instrument driving that palette is titled")
w("*Sleep-Wake **State** (yellow=wake; blue=sleep; black=indeterminate)* — exactly")
w("three categories. AASM staging has exactly **one** wake state and **four** sleep")
w("stages, so the group of four must be the sleep stages and the singleton must be")
w("wake:")
w("")
w(md_table([
    ["`0`", "**indeterminate**", "black (`000000`) in *both* palettes; both legends say black = indeterminate"],
    ["`1` `2` `3` `4`", "**the four sleep stages** (N1/N2/N3/REM, order unknown)", "collapsed to a single colour in `SleepWake`"],
    ["`5`", "**wake**", "the singleton colour in `SleepWake`"],
], ["Code", "Meaning", "Basis"]))
w("")
w("> **Caveat — the colour legend contradicts this and I did not follow it.** The")
w("> title says `yellow=wake`, but `B37400` (amber) is the colour of codes 1–4 and")
w("> `42E4F0` (cyan) is code 5. Taken literally that makes four codes \"wake\" and one")
w("> \"sleep\", which is not a valid staging scheme. The legend is user-authored text")
w("> — it contains the typo `ornage` — so the palette *structure* is trusted over the")
w("> colour names. If you would rather trust the legend, the assignment inverts.")
w("")
w("**Still unresolved: which of codes 1–4 is N1 vs N2 vs N3 vs REM.** Persyst's help")
w("(`Trend Types: Sleep-Wake`) documents only the scale — *Number of Levels: 6")
w("(only), Min/Max: 0-5* — and its Performance Testing section validates the")
w("algorithm on the binary wake/sleep collapse, not per-stage. A web search of")
w("public Persyst documentation and its FDA 510(k) summaries turned up no numeric")
w("code table either. Settling it needs Persyst directly.")
w("")
w("For this recording that ambiguity is mostly academic: code 1 covers 85% of the")
w("record, and this is a comatose post-arrest patient, so a per-stage label would be")
w("of doubtful clinical meaning regardless.")
w("")

w("### 4.6 Observed value ranges vs. documented units")
w("")
w(f"Per-family scale evidence (from `column_value_stats.csv`, file `{REF}`):")
w("")
fam_rows = []
for fam in ["aeeg", "artifact_intensity", "artifact_detector", "electrode_quality",
            "suppression_ratio", "coherence_spectrogram", "spectral_edge",
            "rhythmic_delta", "fft_power", "adr", "alpha_variability"]:
    g = ref[ref.mapper_family == fam]
    if not len(g):
        continue
    fam_rows.append([fam, len(g), fmt(g["min"].min()), fmt(g["median"].median()),
                     fmt(g["max"].max())])
w(md_table(fam_rows, ["Pipeline family", "Cols", "Min (across family)",
                      "Median of medians", "Max (across family)"]))
w("")
w("Two observations that contradict the schema notes and should be checked before")
w("these fields are used analytically:")
w("")
rows = [[f"`{c}`", sem[c]["electrode_quality_global_max"],
         sem[c]["artifact_detector_global_max"], sem[c]["artifact_detector_binary"]]
        for c in CSVS]
w(md_table(rows, ["CSV", "Electrode-quality max", "Artifact-detector max",
                  "Artifact detector is strictly 0/1"]))
w("")
w("- `subcol_schema.ARTIFACT_DETECTOR` documents `units=\"binary 0/1\"`. **It is not")
w("  binary here** — it is continuous on roughly [0, 1.2]. The column *assignment*")
w("  (18 BP-longitudinal channels) is unaffected; the documented **unit** is wrong.")
w("- `ELECTRODE_SIGNAL_QUALITY` documents `0=clean, >1=disconnect`; observed max is")
w("  1.0–1.2, consistent with that note.")
w("- Suppression ratio tops out at 41.6 → percent scale, consistent with the")
w("  2026-06 resolution that V8 Suppression Ratio is 0–100%.")
w("")
w("---")
w("")

# ── 5. Parquet ───────────────────────────────────────────────────────────
w("## 5. How this is reported in the Parquet files")
w("")
w("### 5.1 The Parquet stores raw I-codes, not semantic names")
w("")
w("`qeeg/ingestion/parquet_convert.py` writes `ParsedExport.data` straight to Parquet.")
w("Its column names are the **CSV code-row values verbatim** — `ClockDateTime`,")
w("`Time`, `I1_1`, `I1_2`, … The semantic mapping lives outside the Parquet, in the")
w("sidecar JSON under `.qeeg_cache/sidecars/` (`code_to_description`,")
w("`description_to_codes`), and `common_name` is recomputed from it on every read.")
w("")
w("**Two consequences worth being explicit about:**")
w("")
w("1. **The Parquet is not affected by the §6 naming defects.** It stores I-codes, and")
w("   I-codes are correct (§3.4). The defects appear the moment anything downstream")
w("   asks for `common_name` — exports, the semantic merge, the workbench.")
w("2. **To join this document to a Parquet file, key on the `code` column** (or on")
w("   `panel_pos` via `mmx_instrument_map.csv`). Do not key on `common_name`.")
w("")
rows = []
for c in CSVS:
    p = pqv[c]
    rows.append([f"`{c}`", p["parquet_columns"], p["csv_header_codes"],
                 len(p["columns_dropped_all_null"]),
                 len(p["columns_in_parquet_not_in_header"]),
                 f"{p['parquet_rows']:,}", p["sidecar_n_columns"],
                 f"{p['sidecar_n_data_rows']:,}", p["sidecar_parquet_status"]])
w(md_table(rows, ["CSV", "Parquet cols", "CSV header cells", "Dropped (all-null)",
                  "Extra in Parquet", "Parquet rows", "Sidecar n_columns",
                  "Sidecar n_data_rows", "Status"]))
w("")
w("295 Parquet columns = 293 I-codes + `ClockDateTime` + `Time` (§3.3). Nothing was")
w("dropped and nothing added; row counts agree with the sidecar.")
w("(`sidecar_n_columns` = 294 is I-codes + `Time`; only `ClockDateTime` is excluded")
w("from `code_to_description`.)")
w("")

w("### 5.2 Cell-level equality against the raw CSV text")
w("")
w("Seven data rows per file (first, second, 25%, 50%, 75%, last-1, last) were read")
w("straight out of the CSV with `csv.reader` and compared cell-by-cell to the Parquet")
w("value for every non-timestamp column. Empty CSV cell must be null; numeric cells")
w("compared with 1e-9 relative tolerance.")
w("")
rows = [[f"`{c}`", pqv[c]["spot_check"]["compared"], pqv[c]["spot_check"]["match"],
         len(pqv[c]["spot_check"]["mismatch"]), str(pqv[c]["spot_check_rows"])]
        for c in CSVS]
w(md_table(rows, ["CSV", "Cells compared", "Matched", "Mismatched", "Row indices"]))
w("")
w(f"**{sum(pqv[c]['spot_check']['compared'] for c in CSVS):,} cell comparisons, "
  "0 mismatches.** No column shift, no off-by-one, no truncation.")
w("")

w("### 5.3 Timestamps")
w("")
w("`ClockDateTime` is stored as `datetime64[ns]`, converted from the Excel serial in")
w("the CSV by `qeeg.ingestion.timestamps.excel_serial_to_timestamp`.")
w("")
rows = []
for c in CSVS:
    k = pqv[c]["clock"]
    rows.append([f"`{c}`", k["raw_serial_first"], k["parquet_first"], k["parquet_last"],
                 k["csv_header_TestDate"] + " " + k["csv_header_TestTime"],
                 k["monotonic_increasing"], f"{k['median_step_seconds']:.6f}",
                 f"{k['duration_hours']:.3f}"])
w(md_table(rows, ["CSV", "First Excel serial", "Parquet first", "Parquet last",
                  "CSV header TestDate/TestTime", "Monotonic", "Median step (s)",
                  "Span (h)"]))
w("")
w("The converted first timestamp reproduces the header `TestDate`/`TestTime` to the")
w("second in all three files, the series is strictly increasing, and the nominal")
w("cadence is 1 Hz. Sub-second noise (e.g. `…:32.999999333`) is float rounding in the")
w("Excel serial, ~1 µs — harmless for 1 s trend data, but it means exact timestamp")
w("equality across files will fail; bin or round before joining.")
w("")
w("**The 1 Hz cadence is not continuous — there are recording gaps.** The median step")
w("is 1 s but rows are missing, so wall-clock span exceeds row count:")
w("")
rows = []
for c in CSVS:
    t = tax[c]
    rows.append([f"`{c}`", f"{t['rows']:,}", f"{t['span_seconds']:,.0f}",
                 t["n_gaps_gt_1_5s"], f"{t['total_gap_seconds']:,.0f}",
                 f"{t['largest_gap_seconds']:,.0f}", f"{t['step_min']} – {t['step_max']}"])
w(md_table(rows, ["CSV", "Rows", "Span (s)", "Gaps > 1.5 s", "Missing seconds",
                  "Largest gap (s)", "Step min – max (s)"]))
w("")
w("`20260707_1449_.csv` has a single 5,917 s (98 min) gap; its 24.0 h span covers only")
w("22.3 h of recorded data. Anything that assumes a contiguous 1 Hz axis — including")
w("row-index-based windowing — will be wrong for that file. Use `ClockDateTime`, not")
w("the `Time` row counter.")
w("")
w("> **Unresolved, flagged not guessed:** `eeg_date_correction.csv` in the patient")
w("> folder lists durations of 07:29:26 / 15:13:51 / 08:39:50, which do not match the")
w("> spans measured here (7.93 h / 12.39 h / 23.99 h, in file order). The")
w("> segment→duration pairing in that corrections file does not line up with what the")
w("> CSVs contain. This affects ROSC alignment, not column assignment, and is out of")
w("> scope for this document — but it should be resolved before any time-anchored")
w("> analysis of this patient.")
w("")
w("---")
w("")

# ── 6. Findings ──────────────────────────────────────────────────────────
w("## 6. Findings — columns that are NOT correctly assigned")
w("")
counts = ref["review_flag"].value_counts().to_dict()
ok = int((ref.review_flag == "OK").sum())
w(f"**{ok} of {len(ref)} columns pass the automated checks.** The remaining")
w(f"{len(ref)-ok} are broken down below. Flags are in the §7 table and in")
w("`output/audit_4290_1/column_review_table.csv`.")
w("")
w(md_table([[k, v] for k, v in sorted(counts.items(), key=lambda x: -x[1])],
           ["Review flag", "Columns"]))
w("")
w("> The flag counts understate the problem. `OK` only means *unique, classified,")
w("> legal identifier* — it does **not** mean the name is semantically right. §6.4 and")
w("> §6.9 list columns flagged `OK` that are named after the wrong thing, caught only")
w("> by comparing against the MMX.")
w("")
w("Every defect below is in `qeeg/constants.py` + `qeeg/ingestion/column_mapper.py`.")
w("**Not in the CSVs, and not in the Parquet conversion (§5.2).** Nothing has been")
w("changed — the pipeline is reported as it currently behaves.")
w("")

# 6.1
w("### 6.1 27 relative-power columns fall through to `other` (data loss)")
w("")
w("`classify_family` routes a trend through the ratio-aware `classify_ratio` **only**")
w("if the name matches `FFT[_ ]PowerRatio`. Persyst's display label for these is")
w("`Relative Beta, 13-30/1-30 Hz, …`, which matches no `FEATURE_FAMILIES` pattern, so")
w("they land in `other` with placeholder names. The MMX name shows what they are:")
w("")
sub = ref[ref.trend_name.astype(str).str.startswith(("Relative Beta", "Relative Delta",
                                                     "Relative Theta"))]
w(md_table([[f"`{r.code}`", esc(r.trend_name), f"`{esc(r.mmx_name)}`",
             f"`{r.common_name}`", fmt(getattr(r, "median"))] for r in sub.itertuples()],
           ["I-code", "CSV trend name", "MMX instrument Name", "Current `common_name`",
            "Median"]))
w("")
w("§4.2 confirms these numerically. Expected names would be `rel_beta_all`,")
w("`rel_delta_left_anterior`, … via the existing `relative_power` branch of")
w("`generate_common_name`, which is currently unreachable for them.")
w("")

# 6.2
w("### 6.2 9 `Relative Alpha` columns are mis-assigned to RAV and collide with it")
w("")
w("`FEATURE_FAMILIES['alpha_variability']` includes the literal pattern")
w("`Relative Alpha`. Per the MMX these are `FFT_PowerRatio 8-13//1-30` (relative alpha")
w("power), not RAV (`6-14//1-20`). Both therefore receive the same `rav_*` name:")
w("")
coll = hdr["per_file"][REF]["common_name_collisions"]
rav = {k: v for k, v in coll.items() if k.startswith("rav_")}
rows = []
for k in sorted(rav):
    for e in rav[k]:
        r = ref[ref.code == e["code"]]
        mn = r.mmx_name.iloc[0] if len(r) else ""
        rows.append([f"`{k}`", f"`{e['code']}`", esc(e["trend_name"]), f"`{esc(mn)}`"])
w(md_table(rows, ["Colliding `common_name`", "I-code", "CSV trend name",
                  "MMX instrument Name"]))
w("")
w("§4.3 shows the two are different signals (r ≈ 0.93, max diff ≈ 0.19). Whichever")
w("column is written second wins in any name-keyed structure — including the")
w("multi-segment semantic merge, which keys on `common_name`.")
w("")

# 6.3
w("### 6.3 Remaining `common_name` collisions")
w("")
rows = [[f"`{k}`", len(coll[k]), "<br>".join(f"`{e['code']}`" for e in coll[k])]
        for k in sorted(coll) if not k.startswith("rav_")]
w(md_table(rows, ["`common_name`", "Cols", "Columns sharing it"]))
w("")
w("Adjudicated against the MMX — **these are mostly not display duplicates:**")
w("")
rows = []
for g in [142, 143, 144, 145, 163, 164, 165, 166, 167, 168, 169, 153]:
    r = ig(g)
    if r is None:
        continue
    rows.append([f"`I{g}`", f"`{r.common_name}`",
                 f"`{esc(simplify_mmx(r.mmx_name))[:76]}`"])
w(md_table(rows, ["I-group", "Pipeline `common_name`", "MMX instrument Name (simplified)"]))
w("")
w("Reading that table:")
w("")
w("- **`I144` is Detections, `I145` is Probability** — two different instruments, both")
w("  named `seizure_probability_p14`. They are byte-identical in these files only")
w("  because every seizure column is constant 0 for this patient")
w(f"  (`I144_1 == I145_1`: {sem[REF]['I144_equals_I145']}). In a patient with seizures")
w("  they would differ, and one would silently overwrite the other.")
w("- **`I163` is right hemisphere, `I165` is left hemisphere** — both named")
w("  `spike_threshold_per_10s`. Laterality is lost.")
w("- **`I166`/`I167`/`I168`/`I169` are bilateral / right-only / left-only /")
w("  generalized.** The pipeline names them `spike_left`, `spike_left`,")
w("  `spike_generalized`, `spike_generalized` — so `I166` (bilateral) and `I168`")
w("  (left-only) are also *individually* mislabelled, not merely collided.")
w("- **`I156` vs `I164`** share `spike_generalized_per_sec` but are genuinely")
w(f"  different (`I156_1 == I164_1`: {sem[REF]['I156_equals_I164']}) — a spike")
w("  count/sec versus a rate-threshold boolean.")
w("- **`I153`** is a `ColorScaledBars` display instrument, not a stage indicator, but")
w("  carries `sleep_stage_display` alongside the six one-hot indicators (§4.5).")
w("")

# 6.4
w("### 6.4 The legacy I-group table mislabels 36 columns in this panel")
w("")
w("`get_subcolumn_name` step 2 falls back to `I_GROUP_SUBCOLUMN_NAMES`, keyed by the")
w("**I-group number**. §3.4 shows the I-group number is the *panel position* — specific")
w("to the panel that produced the export. That table was built against a different")
w("panel, so the lookup returns names belonging to a different instrument.")
w("")
w("Worked example: `I20_1` here is `Boolean LPD+`. `qeeg/constants.py` line 89 reads")
w("`20: list(_AEEG_SCHEMA.slugs),  # aEEG Left Hemisphere`, so the lookup returns the")
w("aEEG slug for sub-index 1 → `max` → `pd_max`. `I21_1` (`Boolean LRD+`) hits the")
w("adjacent `21: … # aEEG Right Hemisphere` entry → also `max` → also `pd_max`.")
w("")
w("The same table maps `1 → artifact_intensity`, `2 → artifact_detector`,")
w("`3 → electrode_signal_quality`, whereas in this panel `I1`–`I3` are the aEEG")
w("instruments. Those do **not** misfire only because `get_subcolumn_name` step 1")
w("(the family schema) resolves aEEG first and never reaches the table. The damage is")
w("confined to families that have no schema entry.")
w("")
w("Columns where the bad sub-column name **propagates into `common_name`**, with the")
w("MMX-correct identity alongside:")
w("")
rows = []
for code in ["I19_1", "I20_1", "I21_1", "I22_1", "I23_1", "I24_1",
             "I127_1", "I128_1", "I129_1", "I142_1", "I146_1"]:
    m = ref[ref.code == code]
    if not len(m):
        continue
    r = m.iloc[0]
    rows.append([f"`{code}`", esc(str(r.trend_name))[:32], f"`{r.sub_column_name}`",
                 f"`{r.common_name}`", f"`{esc(simplify_mmx(r.mmx_name))[:70]}`"])
w(md_table(rows, ["I-code", "CSV trend name", "Resolved sub-col name",
                  "Resulting `common_name`", "MMX instrument Name (simplified)"]))
w("")
w("The MMX resolves what these actually are:")
w("")
w("- `I19`–`I24` are LAD / LPD / LRD / RAD / RPD / RRD. `I20` should be `pd_lpd` and")
w("  `I21` should be `pd_lrd`; both are `pd_max`. Note `LRD` is `LAD OR LPD` and `RRD`")
w("  is `RAD OR RPD` — regional, not a third focus.")
w("- `I127`/`I128`/`I129` are **bilateral / left-only / right-only** rhythmic delta")
w("  (`L AND R`, `L AND NOT R`, `R AND NOT L`). They are named `rda_n3`, `rda_rem`,")
w("  `rda_indeterminate` — sleep-stage labels borrowed from the wrong table.")
w("- `I142` is `SeizureEventsP14`, the 2-sub-column detection+notification instrument")
w("  that `subcol_schema.SEIZURE_DETECTION_NOTIF_PAIR` exists to describe. The schema")
w("  is not consulted because `column_mapper`'s `_family_alias` has no entry mapping")
w("  family `seizure_detection` → `seizure_detection_notif_pair`, so sub-col 1 falls")
w("  through to the legacy table and becomes `seizure_threshold_left`.")
w("")
w("For another 25 columns the wrong sub-column name is computed but discarded because")
w("their `generate_common_name` branch ignores `sub_column_name` (e.g. all")
w("`spectral_edge` and `peak_envelope` columns). Those names are correct **by luck**,")
w("and the wrong `sub_column_name` is still visible in the review table.")
w("")

# 6.5
w("### 6.5 Four SEF95 columns unclassified (regex requires no space)")
w("")
w("`FEATURE_FAMILIES['spectral_edge'] = 'FFT_Edge|SEF\\\\d+'` — `SEF95` matches,")
w("`SEF 95` does not. The MMX is unambiguous that all four are SEF95:")
w("")
sef = ref[ref.trend_name.astype(str).str.startswith("SEF 95")]
w(md_table([[f"`{r.code}`", esc(r.trend_name), f"`{esc(r.mmx_name)}`",
             f"`{r.common_name}`",
             f"{fmt(getattr(r,'min'))} – {fmt(getattr(r,'max'))}"]
            for r in sef.itertuples()],
           ["I-code", "CSV trend name", "MMX instrument Name", "Current `common_name`",
            "Observed range"]))
w("")
w("Their ranges match the correctly-classified SEF95 columns "
  f"({fmt(ref[ref.common_name=='sef_95_all']['min'].iloc[0])} – "
  f"{fmt(ref[ref.common_name=='sef_95_all']['max'].iloc[0])}).")
w("")

# 6.6
w("### 6.6 `Coherence_Avg` mislabelled as a spectrogram bin")
w("")
w("`FEATURE_FAMILIES['coherence_spectrogram'] = 'Coherence'` matches `Coherence_Avg`")
w("too, so five single-value 0–32 Hz averages get a spectrogram bin-frequency suffix")
w("of `0.00hz` (the bin-1 centre) — wrong, and not a valid identifier. The sub-column")
w("validator classifies these correctly as `coherence_avg`; the mapper does not. The")
w("MMX confirms the validator: the instrument is `Coherence_Avg`, and it is **not**")
w("one of the 8 spectrograms Persyst excluded from the export (§3.4).")
w("")
coh = ref[ref.mapper_family == "coherence_spectrogram"]
w(md_table([[f"`{r.code}`", f"`{esc(r.mmx_name)}`", f"`{r.common_name}`",
             f"`{r.validator_family}`",
             f"{fmt(getattr(r,'min'))} – {fmt(getattr(r,'max'))}"]
            for r in coh.itertuples()],
           ["I-code", "MMX instrument Name", "Mapper `common_name`", "Validator family",
            "Range"]))
w("")
w("Also note the electrode token keeps only the **left** member of each pair:")
w("`C3-P3*C4-P4` → `c3p3`. The right-hemisphere half of every coherence pair is")
w("absent from the name.")
w("")

# 6.7
w("### 6.7 13 `common_name` values are not valid identifiers")
w("")
w("`generate_common_name` is documented to emit \"a valid Python/R identifier\".")
w("These do not:")
w("")
inv = ref[ref.review_flag.astype(str).str.contains("INVALID")]
w(md_table([[f"`{r.code}`", f"`{r.common_name}`",
             "contains `/`" if "/" in str(r.common_name) else "contains `.`"]
            for r in inv.itertuples()],
           ["I-code", "`common_name`", "Problem"]))
w("")
w("`5uv/hz` will break a `data$col` reference in R and any `df.col` access in pandas;")
w("`1.1hz` likewise.")
w("")

# 6.8
w("### 6.8 Smaller items")
w("")
w("- **`I14_1`** — `Asymmetry, Relative Index (REASI), 4 - 8 Hz, Asym Hemi` is named")
w("  `asymmetry_reasi_hemisphere`, with **no band token**, because `ASYMMETRY_BANDS`")
w("  in `qeeg/constants.py` only defines `0 - 5 Hz`, `6 - 14 Hz`, `0 - 20 Hz`. The")
w("  4–8 Hz (theta) REASI silently loses its band. It does not currently collide, but")
w("  it is indistinguishable from a band-less REASI hemisphere index.")
w("- **`I232_1`** — trend name `Time` (MMX instrument `Time`), unclassified because")
w("  `time_display` requires `^Time[,\\s]` and the bare name has neither. Constant 0.")
w("  Distinct from the `Time` *column* in §3.3.")
w(f"- **`I231_1`** — `Comment`, correctly classified as `annotation`, and **constant 0**.")
w(f"  This is not an empty recording: the `.lay` for this segment holds")
w(f"  {sc['comment']['n_comments_in_lay']} annotations including clinical text")
w("  (`pt intubated, on NIRS, moberg, dialysis`, `low voltage`, `GMZJ diffuse")
w(f"  delta`). Probing the CSV column at all {sc['comment']['n_probed_offsets']}")
w(f"  comment offsets gives {sc['comment']['n_nonzero_at_comment_offsets']} non-zero")
w("  values. **The annotation text lives in the `.lay` `[Comments]` section, not in")
w("  the CSV** — the CSV column is a display placeholder that exports no payload.")
w("  Anything needing comments/annotations must parse the `.lay`.")
w("- **`I112_1`** — `PeakEnvelope, 2 - 20 Hz, All 10-20` is named bare")
w("  `peak_envelope` while its eight siblings carry a location suffix. Inconsistent,")
w("  not colliding.")
w("- **`I7_3`** (`artifact_intensity_eye_horizontal`) is constant 0 and `I7_2`")
w("  (`eye_vertical`) has only 2 distinct values in the reference file. Correctly")
w("  assigned; just near-empty for this recording.")
w("- All seizure columns (`I142`–`I145`) are **constant 0** across all three files, so")
w("  no data-driven check can separate them. Their identity rests on the MMX alone")
w("  here — which is exactly why §3.4 matters.")
w("")

# 6.9
w("### 6.9 Summary of semantically wrong names")
w("")
w("Consolidated list of columns whose `common_name` names the wrong thing, per the")
w("MMX. Some are caught by the automated flags, some are not:")
w("")
wrong = [
    ("I20_1", "pd_lpd", "left posterior delta, not an aEEG max"),
    ("I21_1", "pd_lrd", "left regional delta (LAD OR LPD)"),
    ("I127_1", "rda_bilateral", "rhythmic delta L AND R"),
    ("I128_1", "rda_left", "rhythmic delta L AND NOT R"),
    ("I129_1", "rda_right", "rhythmic delta R AND NOT L"),
    ("I142_1", "seizure_detection_event", "SeizureEventsP14 sub-col 1"),
    ("I144_1", "seizure_detection_p14", "SeizureProbabilityP14 Detections"),
    ("I146_1", "sleep_stage_code", "SleepStages categorical output"),
    ("I153_1", "sleep_stage_bars", "ColorScaledBars display of the same"),
    ("I163_1", "spike_threshold_right_per_10s", "right-hemisphere spike-rate threshold"),
    ("I165_1", "spike_threshold_left_per_10s", "left-hemisphere spike-rate threshold"),
    ("I166_1", "spike_bilateral", "L AND R"),
    ("I167_1", "spike_right", "R AND NOT L"),
    ("I168_1", "spike_left", "L AND NOT R"),
    ("I169_1", "spike_generalized", "SpikeGen"),
]
rows = []
for code, suggested, why in wrong:
    m = ref[ref.code == code]
    if not len(m):
        continue
    r = m.iloc[0]
    rows.append([f"`{code}`", f"`{r.common_name}`", f"`{suggested}`", why, r.review_flag])
w(md_table(rows, ["I-code", "Current `common_name`", "Suggested", "MMX basis",
                  "Automated flag"]))
w("")
w("`Suggested` is a proposal for discussion, not a change that has been made.")
w("Renaming `common_name` changes every downstream export and the semantic-merge key,")
w("so it is a cohort-relock decision.")
w("")
w("---")
w("")

# ── 7. Full table ────────────────────────────────────────────────────────
w("## 7. Full per-column table")
w("")
w(f"All {len(ref)} named columns other than `ClockDateTime`, in CSV column order, from")
w(f"`{REF}` — 293 I-codes plus the unassigned `Time` column. §3.1 established the")
w("other two files are identical in layout, so this table applies to all three.")
w("Value statistics are from that file's Parquet; the MMX column is the authoritative")
w("identity from §3.4.")
w("")
w("Machine-readable copy with all three files and more columns:")
w("`output/audit_4290_1/column_review_table.csv`.")
w("")
w("Legend — `Flag`: `OK` passes the automated checks (unique, classified, legal")
w("identifier — **not** a guarantee of semantic correctness, see §6.9);")
w("`UNCLASSIFIED` family is `other`; `COLLISION(xN)` name shared with N−1 other")
w("columns; `INVALID_IDENTIFIER` name is not a legal Python/R identifier;")
w("`NO_ASSIGNMENT` no `ColumnEntry` was built at all.")
w("")
rows = []
for r in ref.itertuples():
    rows.append([
        r.csv_col_index, f"`{r.code}`",
        (f"{int(r.panel_pos)}" if pd.notna(r.panel_pos) else ""),
        (esc(r.trend_name)[:58] if isinstance(r.trend_name, str)
         else "*(blank — no trend name in header)*"),
        (f"`{esc(simplify_mmx(r.mmx_name))[:58]}`" if isinstance(r.mmx_name, str) else ""),
        r.mapper_family if isinstance(r.mapper_family, str) else "*(unassigned)*",
        f"`{r.common_name}`" if isinstance(r.common_name, str) else "*(none)*",
        r.review_flag,
        f"{fmt(r.min)} … {fmt(r.max)}", fmt(getattr(r, "median")), r.n_distinct,
    ])
w(md_table(rows, ["Col", "I-code", "Panel #", "CSV trend name",
                  "MMX instrument Name", "Family", "`common_name`", "Flag",
                  "Min … Max", "Median", "Distinct"]))
w("")
w("---")
w("")

# ── 8. Channel-order investigation ───────────────────────────────────────
cod = json.loads((AUD / "channel_order_derivation.json").read_text(encoding="utf-8"))
ev = cod["structural_evidence"]
ca = cod["correlation_attempt"]

w("## 8. Sub-column channel identity for `I6`, `I7`, `I30` (43 columns)")
w("")
w("These three instruments are the only ones whose per-sub-column meaning comes")
w("**entirely** from a hardcoded list in `subcol_schema.py` — the MMX gives no help")
w("(`Channels` is empty for all three, and the MMX's `<Channels>` and")
w("`<ChannelGroupDefinitions>` sections are empty), and unlike aEEG there is no")
w("ordering property that a data check could exploit.")
w("")
w("### 8.1 The sources disagree — three ways")
w("")
rows = [
    ["Persyst 15 help, *Trend Types: Artifact*",
     "ESQ = artifact “in individual channels of **the montage** being used for EEG "
     "trend measure calculations”", "montage derivations"],
    ["`PersystTrendCSV_Format_Reference.md` §3.3",
     "ESQ = “per **acquisition-system channel** (not per BP-Longitudinal derivation "
     "— this is a frequent point of confusion)”; count “equals the number of "
     "acquisition channels in the source `.dat`”", "acquisition electrodes"],
    ["`docs/PERSYST_V10_REFERENCE.md` §3 table",
     "ElectrodeSignalQuality sub-cols = **18**", "18 (contradicts the observed 22)"],
    ["`qeeg/ingestion/subcol_schema.py`",
     "ESQ = 22 named electrodes incl. **EKG**, no Fpz; Artifact Detector = 18 "
     "**single electrodes** incl. A1/A2", "as coded"],
    ["`4290-1_1684730.lay` `[ChannelMap]`",
     "22 EEG acquisition electrodes: 19×10-20 + A1 + A2 + **Fpz**", "acquisition list"],
    ["`4290-1_1684730.lay` `[Record Montage 1]`",
     "18 EEG **bipolar derivations** + X3-X4 + A1+A2 + 5 averages", "montage list"],
]
w(md_table([[a, b, c] for a, b, c in rows], ["Source", "What it says", "Implies"]))
w("")
w("The format reference's own §3.3 warns: *“Don't assume the 18-row table below")
w("applies to your file. Always derive the sub-col → electrode mapping from the")
w("recording's actual channel list.”* That is what this section does.")
w("")

w("### 8.2 Evidence A — raw per-instrument outputs confirm the widths")
w("")
w("Persyst writes one binary per instrument under `4290-1_1684730.Persyst/`. File")
w("size is proportional to channel count at a fixed epoch rate:")
w("")
w(md_table([[f"`{k}`", f"{v:,}"] for k, v in sorted(ev["raw_output_sizes"].items())],
           ["Raw output", "Bytes"]))
w("")
w(f"`ElectrodeSignalQuality / Artifact` = **{ev['esq_over_ad_size_ratio']}** versus")
w(f"22/18 = **{ev['expected_22_over_18']}**. The widths 22 and 18 are confirmed")
w("independently of the CSV.")
w("")

w("### 8.3 Evidence B — Persyst names its own trending channels, and there are 18")
w("")
w("The same folder contains one file per trending channel for the per-channel")
w(f"rhythmicity instrument. Exactly **{ev['n_persyst_bipolar_pairs']}** are bipolar")
w("pairs:")
w("")
w("```")
w("  " + "  ".join(ev["persyst_bipolar_pairs"]))
w("```")
w("")
w("That is precisely the 18 EEG derivations in the `.lay` `[Record Montage 1]`, and")
w("it is exactly the width of `I6`. Combined with the Persyst help wording")
w("(“channels of the montage”), **`I6` Artifact Detector is per bipolar derivation,")
w("not per electrode.**")
w("")
w("> **Defect.** `subcol_schema.ARTIFACT_DETECTOR` lists 18 *single electrodes*")
w("> (`Fp1, F3, C3, P3, O1, F7, T3, T5, Fp2, F4, C4, P4, O2, F8, T4, T6, A1, A2`).")
w("> That is wrong in kind, not just in order — and `A1`/`A2` do not appear in the")
w("> trending montage at all. All 18 `artifact_detector_*` names are misleading.")
w("")

w("### 8.4 Evidence C — ESQ width does not follow the acquisition channel count")
w("")
w("The format reference says the ESQ sub-col count equals the number of acquisition")
w("channels. Testing that across every recording on the share:")
w("")
rows = [[f"`{c['recording']}`", c["eeg_like_channels"], c.get("esq"),
         c.get("artifact_detector"), c.get("artifact_intensity"),
         ", ".join(c["extra_named_channels"]) or "—"] for c in ev["cross_recording"]]
w(md_table(rows, ["Recording", "Named non-X/DC acquisition channels", "ESQ sub-cols",
                  "Artifact Detector", "Artifact Intensity", "Extra channels"]))
w("")
w("`4290-13_e25cb83` records **28** named channels — six more than the others")
w("(`EKGL, EKGR, LOC, ROC, RESP1, RESP2`) — and still exports **22** ESQ")
w("sub-columns. ESQ width is constant at 22 across all seven recordings while the")
w("acquisition count varies.")
w("")
w("> **Defect.** The format reference §3.3 claim *“the number of sub-columns equals")
w("> the number of acquisition channels in the source `.dat` file”* is refuted.")
w("> `docs/PERSYST_V10_REFERENCE.md`'s claim of **18** ESQ sub-columns is also wrong.")
w("")
w("It also refutes the `EKG` entry in the schema's ESQ list: `4290-13` has *two* EKG")
w("channels and still emits 22, so EKG is not one of the 22. In every recording the")
w("`.lay` `[ChannelMap]` positions 1–22 are 19×10-20 + `A1` + `A2` + one")
w("recording-specific extra — `Fpz` in 4290-1, `Nasion` in 4290-13. A fixed list")
w("could not accommodate both; a positional read of `[ChannelMap]` can.")
w("")

w("### 8.5 Evidence D — the data cannot resolve the ordering (negative result)")
w("")
w("Attempted derivation: if `I6_j` is a derivation and `I30_k` an electrode, the two")
w("`I30` columns most associated with `I6_j` should be exactly that derivation's two")
w("electrodes — which would recover the montage graph, and hence both orderings,")
w("from data alone. **It does not work here.**")
w("")
rows = [[f"`{c}`", f"{ca[c]['n_rows']:,}", ca[c]["min_r_top2"], ca[c]["min_separation"],
         str(ca[c]["eq_indices_never_selected"])] for c in CSVS]
w(md_table(rows, ["CSV", "Rows", "Min r of 2nd pick", "Min separation vs 3rd",
                  "ESQ indices never selected"]))
w("")
w("Correlations are near zero and the recovered graph differs completely between")
w("files — the signals are ~99% zero, so rank correlation is noise. Thresholded")
w("co-occurrence on sustained badness does better but is degenerate:")
w("")
w("- In `20260707_1413_.csv`, `I30_3`, `I30_5`, `I30_14` are bad for 99.85% of the")
w("  recording and `I30_22` for 88.64% — a real disconnect event. But the three")
w("  99.85% channels are **byte-identical in time** (they went open together), so")
w("  nothing can distinguish them from each other.")
w("- `I30_22` (88.64%) co-occurs with exactly `I6_10` and `I6_18` (Jaccard 0.999 and")
w("  0.998). **One electrode ↔ exactly two derivations** — consistent with the")
w("  bipolar reading of §8.3, and the only positive pairing recoverable.")
w("- The three simultaneously-dead electrodes produce only two dead `I6` columns,")
w("  and those two (`I6_4`, `I6_5`) are also byte-identical.")
w("- In `20260707_1449_.csv`, `I30_3`/`I30_14` are bad for 2.7% of rows and **no**")
w("  `I6` column is elevated in that window at all.")
w("")
w("So the ordering is **not resolvable from these recordings**. Reported as a")
w("negative result rather than forced.")
w("")

w("### 8.6 Verdict")
w("")
rows = [
    ["`I6` Artifact Detector — *kind*", "**Resolved: 18 bipolar montage derivations**",
     "§8.2, §8.3, §8.5 (1↔2 pairing); Persyst help"],
    ["`I6` — *order*", "Unresolved", "`.lay [Record Montage 1]` order is the leading candidate, untested"],
    ["`I30` ESQ — *width rule*", "**Resolved: fixed 22 here, NOT acquisition count**", "§8.4"],
    ["`I30` — *composition*", "**EKG almost certainly wrong**; 22nd slot is a recording-specific electrode (Fpz / Nasion)", "§8.4"],
    ["`I30` — *order*", "Unresolved", "`.lay [ChannelMap]` positions 1–22 is the leading candidate, untested"],
    ["`I30` — montage vs acquisition", "Unresolved — sources directly contradict", "§8.1"],
    ["`I7` Artifact Intensity (3)", "Unverified", "`_1` EMG is plausible by scale (µV, median 17.6); `_2`/`_3` near-constant 0 here"],
]
w(md_table(rows, ["Question", "Status", "Basis"]))
w("")
w("**Net effect on the 43 columns:** all 18 `artifact_detector_*` names are wrong in")
w("kind and should be replaced with derivation names; all 22 `electrode_quality_*`")
w("names are of the right kind but at least one label (`EKG`) is wrong and the order")
w("is unproven; the 3 `artifact_intensity_*` names are unverified. **None of these")
w("43 columns should be used with their current labels in a publication** until the")
w("ordering is settled.")
w("")
w("### 8.7 What would settle it")
w("")
w("1. **Ask Persyst** for the sub-column emission order of `Artifact` and")
w("   `ElectrodeSignalQuality` — one email, definitive.")
w("2. **A deliberate single-electrode disconnect.** Pull one electrode at a known")
w("   time on a test recording; the ESQ column that goes high names itself, and the")
w("   two `I6` columns that follow name the derivation pair. Repeat per electrode, or")
w("   stagger the disconnects in time so they are not co-temporal — that is precisely")
w("   what defeated §8.5.")
w("3. **Read the `.raw` binaries directly.** `mg2.ElectrodeSignalQuality.raw` and")
w("   `mg2.Artifact.raw` are fixed-width channel-interleaved; if a header or the")
w("   `.Persyst` sidecars carry channel labels, that resolves it without new data.")
w("")
w("---")
w("")

# ── 9. Reproduce ─────────────────────────────────────────────────────────
w("## 9. Reproducing this")
w("")
w("```bash")
w("python scripts/audit_4290_1_columns.py --headers   # header scan, no data rows read")
w("python scripts/audit_4290_1_columns.py --parquet   # full parse + convert + verify")
w("python scripts/audit_4290_1_columns.py --stats     # value stats + semantic checks")
w("python scripts/audit_4290_1_columns.py --mmx       # panel alignment + identity merge")
w("python scripts/derive_4290_1_channel_order.py      # §8 channel-identity evidence")
w("python scripts/audit_sleep_and_comment.py          # §4.5 sleep codes + §6.8 Comment")
w("python scripts/gen_4290_1_review_doc.py            # regenerate this document")
w("```")
w("")
w("Evidence files in `output/audit_4290_1/`:")
w("")
w("| File | Contents |")
w("|---|---|")
w("| `header_audit.json` | metadata, sub-col contract result, name-keyed MMX coverage, collisions, cross-file identity |")
w("| `column_assignments.csv` | every column × every assignment field, all 3 CSVs |")
w("| `column_value_stats.csv` | per-column dtype, null rate, min/p01/median/p99/max, distinct count |")
w("| `parquet_verification.json` | column/row identity, cell-level spot check, timestamp check |")
w("| `semantic_checks.json` | §4.1–§4.4, §4.6 numeric checks |")
w("| `sleep_onehot_check.json` | §4.5 |")
w("| `time_axis_check.json` | §3.3 column inventory, §5.3 gap analysis |")
w("| `mmx_alignment.json` | §3.4 panel alignment result + excluded spectrograms |")
w("| `sleep_and_comment.json` | §4.5 sleep-code deduction from MMX palettes; §6.8 Comment-column probe |")
w("| `mmx_instrument_map.csv` | I-group → panel position → MMX instrument definition |")
w("| `column_review_table.csv` | the §7 table, all 3 CSVs, with flags and MMX identity |")
w("| `channel_order_derivation.json` | §8 — raw-output sizes, Persyst per-channel names, cross-recording widths, failed correlation derivation |")
w("")

DOC.parent.mkdir(parents=True, exist_ok=True)
DOC.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {DOC} ({len(L)} lines)")
