"""Emit docs/COLUMN_ASSIGNMENT_REVIEW_FULLPANEL.md from the audit evidence.

Companion to the limited-panel review. Tables are generated from
output/audit_fullpanel/*.json / *.csv so the doc cannot drift.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AUD = ROOT / "output" / "audit_fullpanel"
LIM = ROOT / "output" / "audit_subject-1"
DOC = ROOT / "docs" / "COLUMN_ASSIGNMENT_REVIEW_FULLPANEL.md"

pv = json.loads((AUD / "parquet_verification.json").read_text(encoding="utf-8"))
sm = json.loads((AUD / "summary.json").read_text(encoding="utf-8"))
seam = json.loads((AUD / "segment_seam.json").read_text(encoding="utf-8"))
limpv = json.loads((LIM / "parquet_verification.json").read_text(encoding="utf-8"))
tbl = pd.read_csv(AUD / "column_review_table.csv")
lm = json.loads((AUD / "mmx_label_match.json").read_text(encoding="utf-8"))
lm_lim = json.loads((LIM / "mmx_label_match.json").read_text(encoding="utf-8"))


def md_table(rows, head):
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


L = []
w = L.append

w("# Column-assignment review — patient subject-1, **full research panel**")
w("")
w("Companion to [`COLUMN_ASSIGNMENT_REVIEW.md`](COLUMN_ASSIGNMENT_REVIEW.md),")
w("which covers the three limited-panel CSVs. This one covers")
w(f"`{pv['csv']}` ({pv['csv_bytes']/1e9:.20f} GB).")
w("")
w("Generated by `scripts/audit_fullpanel.py` + `scripts/gen_fullpanel_doc.py`.")
w("")
w("> **Headline: this file is not a clean single-segment export.** It is two")
w("> concatenated export blocks from *different* recording segments, joined by a")
w("> truncated row, and its header attributes the whole thing to one segment. §2.")
w("")
w("---")
w("")

# 1
w("## 1. What was processed")
w("")
w(md_table([
    ["CSV", f"`{pv['csv']}`"],
    ["Size", f"{pv['csv_bytes']/1e9:.20f} GB"],
    ["Declared source `.dat` (header `File,` row)", f"`{Path(pv['source_dat']).name}`"],
    ["Derived patient id", f"`{pv['derived_patient_id']}`"],
    ["Data rows", f"{pv['parquet_rows']:,}"],
    ["I-code columns", f"{sm['n_icode_columns']:,}"],
    ["Instruments (I-groups)", f"{sm['n_instruments']}"],
    ["Parquet columns", f"{pv['parquet_columns']:,}"],
    ["Parquet", f"`{Path(pv['parquet_path']).name}` ({pv['parquet_bytes']/1e6:.0f} MB)"],
], ["Field", "Value"]))
w("")
w("Versus the limited panel: **369 instruments / 4,103 columns** here against")
w("232 / 293 there — the difference is almost entirely the multi-column spectrogram")
w("families, which the limited panel excludes entirely.")
w("")
w("---")
w("")

# 2 — seam
w("## 2. The file contains two segments, not one")
w("")
w(f"`Time` (the 0-based row counter, §3.3 of the companion doc) is **not monotonic**.")
w(f"It resets exactly once, at data row **{seam['seam_data_row_indices'][0]:,}**.")
w("")
w("Row widths straight from the CSV text at that point:")
w("")
w(md_table([[f"data row {k}", v, "✅ full" if v == seam["expected_row_width"] else "⚠️ **truncated**"]
            for k, v in seam["row_widths_at_seam"].items()],
           ["Row", "Columns in raw CSV", "Status"]))
w("")
w(f"The seam row has **{seam['row_widths_at_seam'][str(seam['seam_data_row_indices'][0])]} of")
w(f"{seam['expected_row_width']}** columns and an empty timestamp — a partially written")
w("row where the export was interrupted and restarted.")
w("")
w("### 2.1 What each block is")
w("")
rows = []
for i, b in enumerate(seam["blocks"]):
    prov = next((p for p in seam["block_provenance"] if p["block"] == i), None)
    rows.append([
        i, f"{b['rows'][0]:,}–{b['rows'][1]:,}", f"{b['n_rows']:,}",
        f"{b['time_min']:,}–{b['time_max']:,}",
        b["first_ts"][:19], b["last_ts"][:19],
        f"`{prov['matches_csv']}`" if prov else "—",
    ])
w(md_table(rows, ["Block", "Rows", "N", "`Time` range", "First timestamp",
                  "Last timestamp", "Identical to"]))
w("")
w("Both blocks were matched by comparing their **full `ClockDateTime` sequences**")
w("against the already-verified limited-panel exports:")
w("")
rows = []
for p in seam["block_provenance"]:
    rows.append([p["block"], f"`{p['matches_csv']}`", p["identical"],
                 f"{p['offset_rows_into_that_export']:,}",
                 f"{p['that_export_total_rows']:,}",
                 f"{p['rows_missing_before_offset']:,}"])
w(md_table(rows, ["Block", "Matches export", "Timestamps identical",
                  "Starts at row N of that export", "That export's total rows",
                  "Rows missing before it"]))
w("")
w("So:")
w("")
w("- **Block 0** is the *complete* `subject-1_rec-3.dat` segment — byte-identical")
w("  timestamps to `20260707_1413_.csv`.")
w("- **Block 1** is the *tail* of the `subject-1_rec-2.dat` segment: rows 38,566–80,371")
w("  of `20260707_1449_.csv`. **The first 38,566 rows of that segment are absent from")
w("  this file** — roughly the first 12.4 hours of the `-2` recording.")
w("")
w("### 2.2 Why this matters")
w("")
w("1. **The header lies about scope.** `File,` says")
w(f"   `{Path(pv['source_dat']).name}`, and `qeeg.ingestion.identity` derives the")
w("   patient from it. Every downstream consumer will treat all")
w(f"   {pv['parquet_rows']:,} rows as segment `-3`, when")
w(f"   {seam['blocks'][1]['n_rows']:,} of them ({100*seam['blocks'][1]['n_rows']/pv['parquet_rows']:.0f}%)")
w("   are segment `-2`.")
w("2. **Timestamps go backwards at the seam** — block 1 starts at")
w(f"   `{seam['blocks'][1]['first_ts'][:19]}`, which is *earlier* than block 0's end")
w(f"   (`{seam['blocks'][0]['last_ts'][:19]}`). Any time-ordered analysis, ROSC")
w("   alignment, or `.diff()`-based cadence check is invalid across the whole file.")
w("3. **The truncated row is silently ingested.** `pandas.read_csv` pads a short row")
w("   with NaN rather than rejecting it, so it becomes a legitimate-looking all-null")
w(f"   data row at index {seam['seam_data_row_indices'][0]:,} "
  f"(the only null `ClockDateTime` in the file).")
w("4. **Rows are duplicated across the cohort.** Every row in this file also exists in")
w("   `20260707_1413_.csv` or `20260707_1449_.csv`. Loading all four files without")
w("   de-duplication double-counts ~86k epochs.")
w("")
w("> **Recommendation:** do not use this file as a segment source. Its only unique")
w("> contribution is the *spectrogram columns*; its scalar trends are duplicates of")
w("> the limited-panel exports. If the spectrograms are needed, split it at the seam")
w("> and re-attribute each block to its true `.dat`.")
w("")
w("---")
w("")

# 3 — parquet fidelity
w("## 3. Parquet fidelity — clean")
w("")
w("The conversion itself is faithful; the problems above are in the source CSV.")
w("")
w(md_table([
    ["Parquet columns", f"{pv['parquet_columns']:,}"],
    ["CSV header cells", f"{pv['csv_header_cells']:,}"],
    ["Columns dropped (all-null)", len(pv["columns_dropped_all_null"])],
    ["Columns in Parquet not in header", len(pv["columns_in_parquet_not_in_header"])],
    ["Parquet rows", f"{pv['parquet_rows']:,}"],
    ["Sidecar n_data_rows", f"{pv['sidecar_n_data_rows']:,}"],
    ["Sidecar status", pv["sidecar_parquet_status"]],
    ["Cells compared vs raw CSV text", f"{pv['spot_check']['compared']:,}"],
    ["Matched", f"{pv['spot_check']['match']:,}"],
    ["**Mismatched**", f"**{len(pv['spot_check']['mismatch'])}**"],
    ["dtypes", ", ".join(f"{k}: {v}" for k, v in pv["dtype_counts"].items())],
], ["Check", "Result"]))
w("")
w(f"**{pv['spot_check']['compared']:,} cell comparisons across 7 sampled rows, "
  "0 mismatches.** No column shift, nothing dropped or added.")
w("")
w("---")
w("")

# 4 — spectrograms
w("## 4. Spectrogram families — widths CONFIRMED")
w("")
w("These four families appear in **no** limited-panel export, so this file is the")
w("first test of their `subcol_schema` definitions.")
w("")
rows = []
for fam, s in sm["spectrogram_checks"].items():
    rows.append([f"`{fam}`", f"`{s['i_group']}`", s["observed_width"],
                 s["expected_width"], "✅" if s["width_ok"] else "❌",
                 f"{s['global_min']} … {s['global_max']}",
                 s["median_profile_peak_bin"],
                 s["peak_bin_freq_hz"] if s["peak_bin_freq_hz"] is not None else "—"])
w(md_table(rows, ["Family", "I-group sampled", "Observed width", "Expected",
                  "OK", "Value range", "Peak bin of median profile", "→ Hz"]))
w("")
w(f"**All widths match, and the sub-column contract validator reports")
w(f"{len(sm['subcol_mismatches'])} violations across all {sm['n_instruments']} instruments.**")
w("")
w("Value ranges are consistent with the documented units:")
w("")
w("- `asymmetry_spectrogram` spans −84.7 … +71.5 → the documented % (−100…+100).")
w("- `coherence_spectrogram` spans 0 … 0.997 → squared coherence 0–1.")
w("- `fft_spectrogram` is non-negative (0 … 4.42), consistent with µV/√Hz.")
w("")
w("> **Still not verified: the bin-frequency *formulas*.** The peak of the median")
w("> profile lands at 1.5 Hz (FFT) and 1.0 Hz (rhythmicity), which is where a")
w("> delta-dominant post-arrest recording *should* peak — corroborating, but it")
w("> cannot distinguish the assumed axis from a similar one. Widths are proven;")
w("> the mapping bin→Hz is not.")
w("")
w("---")
w("")

# 5 — assignment
w("## 5. Column assignment")
w("")
w(md_table([[k, f"{v:,}"] for k, v in sm["flag_counts"].items()],
           ["Review flag", "Columns"]))
w("")
w(f"**Only {sm['flag_counts'].get('OK', 0)} of {len(tbl):,} columns pass all checks.**")
w("")
w("### 5.1 91% of columns are not valid identifiers")
w("")
inv = tbl[tbl.review_flag.astype(str).str.contains("INVALID")]
w(f"**{len(inv):,} columns** carry a `common_name` that is not a legal Python/R")
w("identifier, because every spectrogram bin name embeds the bin frequency with a")
w("decimal point:")
w("")
w(md_table([[f"`{r.code}`", f"`{r.common_name}`"] for r in
            inv[inv.mapper_family == "rhythmicity"].tail(3).itertuples()] +
           [[f"`{r.code}`", f"`{r.common_name}`"] for r in
            inv[inv.mapper_family == "fft_spectrogram"].head(2).itertuples()] +
           [[f"`{r.code}`", f"`{r.common_name}`"] for r in
            inv[inv.mapper_family == "coherence_spectrogram"].head(2).itertuples()],
           ["I-code", "`common_name`"]))
w("")
w("By family:")
w("")
w(md_table([[f"`{k}`", f"{v:,}"] for k, v in
            inv.mapper_family.value_counts().items()], ["Family", "Invalid names"]))
w("")
w("`df.rhythmicity_p8o2_23.77hz` is a syntax error in Python and")
w("`data$rhythmicity_p8o2_23.77hz` fails in R. Any export of this file needs the bin")
w("label rewritten (e.g. `_23p77hz` or `_bin94`) before it is usable.")
w("")
w("### 5.2 Collisions and unclassified columns")
w("")
w(f"{sm['n_collisions']} distinct `common_name` values are shared by")
w(f"{sm['n_columns_in_collision']} columns; {sm['n_unclassified']} columns are")
w("unclassified (`other`).")
w("")
w(md_table([[f"`{k}`", f"x{v}"] for k, v in sm["worst_collisions"][:10]],
           ["`common_name`", "Columns"]))
w("")
w("These are the **same defects** documented in the companion doc §6 — the")
w("`Relative Alpha`→RAV mis-assignment, the `SEF 95` regex gap, the legacy I-group")
w("table, the `Coherence_Avg` mislabel — reproduced here on a different panel, which")
w("confirms they are pipeline defects and not panel-specific quirks.")
w("")
w("---")
w("")

# 6 — MMX
w("## 6. MMX provenance — resolved by label composition")
w("")
w("For the limited-panel exports, `I{n}` maps to the *n*-th instrument of the V8")
w("`Research-Trends` panel (232/232, zero mismatches). **That positional rule does")
w("not reproduce here** — the export order matches no panel:")
w("")
w(md_table([
    ["Instruments-section document order", "❌ 330 mismatches of 369"],
    ["Per-recording `.mg2.mmx` Instruments order", "❌ 315 mismatches of 369"],
    ["Any single `<Panel>` ref order", "❌ no panel has 369 refs in this order"],
    ["Union of all panels, first occurrence wins", "❌ 357 mismatches"],
], ["Positional hypothesis", "Result"]))
w("")
w("**But the V8 MMX still resolves the file — by reconstructing the label instead of")
w("the order.** Persyst composes each CSV trend label from the instrument definition:")
w("")
w("```")
w("base instrument    :  {GraphTitle}[, {FreqMin} - {FreqMax} Hz][, {Channels}]")
w("ratio instrument   :  {GraphTitle}, {n_lo}-{n_hi}/{d_lo}-{d_hi} Hz, {Channels}")
w("derived instrument :  {GraphTitle}, {label of the instrument named in Channels}")
w("```")
w("")
w("`Channels` is a channel-set name for base instruments and a bracketed expression")
w("naming a parent instrument for derived ones, so the rule is recursive. Worked")
w("example, resolved three levels deep:")
w("")
w("```")
w("Rhythmicity Spectrogram 3.00 Left Anterior_avg")
w("  GraphTitle 'Rhythmicity Spectrogram FreqPow LA ' + '1 - 25 Hz' + 'Left Anterior'")
w("  -> 'Rhythmicity Spectrogram FreqPow LA , 1 - 25 Hz, Left Anterior'")
w("SumValues_Abs_0-0 [ ... ]")
w("  GraphTitle 'SumValues LA delta freq' + ', ' + parent label")
w("  -> 'SumValues LA delta freq, Rhythmicity Spectrogram FreqPow LA , 1 - 25 Hz, Left Anterior'")
w("```")
w("")
w("…which is exactly the CSV trend name for `I170` in the limited-panel export.")
w("Implemented in `scripts/mmx_label_resolver.py`. Result on this file:")
w("")
w(md_table([
    ["CSV instruments", f"{lm['n_csv_instruments']}"],
    ["MMX instruments", f"{lm['n_mmx_instruments']}"],
    ["**Resolved to exactly one MMX instrument**", f"**{lm['n_resolved_unique']}**"],
    ["Ambiguous (identical MMX definitions)", f"{lm['n_ambiguous']}"],
    ["Unmatched", f"{lm['n_unmatched']} (`Comment` — not present in the MMX `<Instruments>` section)"],
    ["MMX instruments claimed by two I-groups", f"{len(lm['mmx_instruments_claimed_twice'])}"],
], ["Metric", "Result"]))
w("")
w(f"**{lm['n_resolved_unique']} of {lm['n_csv_instruments']} instruments now have an")
w("authoritative MMX identity**, up from 259 by naive name matching.")
w("")
w("The 8 instruments claimed by two I-groups are not errors — the `Research` panel")
w("contains exactly 8 duplicate instrument references, so those instruments really")
w("are exported twice (display duplicates).")
w("")
w("### 6.1 The 17 that cannot be resolved by label — and why that matters")
w("")
w("These are instruments whose MMX definitions are **identical** (same `GraphTitle`,")
w("same `Channels`), so no label-based method can separate them:")
w("")
w(md_table([[f"`{k}`", ", ".join(f"`{x[:44]}`" for x in v[:3])]
            for k, v in list(lm["ambiguous_detail"].items())[:8]],
           ["I-group", "Candidate MMX instruments"]))
w("")
w("The six `= N <0> [SleepStages]` indicators are the clearest case — all six share")
w("the trend label, and only their panel position distinguishes them. In the")
w("limited-panel export §4.5 resolved them from the data (stage codes 1, 0, 3, 5, 4,")
w("2 in panel order). **The same ambiguity is what makes `common_name` collide")
w("(§5.2)** — it is inherent in Persyst's labelling, not a pipeline bug.")
w("")
w("### 6.2 Cross-validation of the resolver")
w("")
w("The resolver was run against the limited-panel export, where an independent")
w("panel-position mapping already exists (companion doc §3.4, proven 232/232):")
w("")
w(md_table([
    ["Instruments resolved by label", f"{lm_lim['n_resolved_unique']} of {lm_lim['n_csv_instruments']}"],
    ["Agree with panel-position mapping", "**215 of 216**"],
    ["Disagree", "1 — `I232`, where `GraphTitle='Time'` collides with a bare instrument named `Time`; panel position is authoritative there"],
], ["Check", "Result"]))
w("")
w("Two independent methods agreeing on 215 of 216 is good evidence the label")
w("reconstruction is correct. It also exposes its one failure mode: a `GraphTitle`")
w("that happens to equal another instrument's `Name`.")
w("")
w("> **Status for this file:** per-column identity is **established for")
w(f"> {lm['n_resolved_unique']} of {lm['n_csv_instruments']} instruments** and")
w("> ambiguous-within-a-known-small-set for 17. That is materially stronger than a")
w("> name lookup, but still one notch below the limited-panel review, where the")
w("> positional proof is exact and complete.")
w("")
w("---")
w("")

w("## 7. Reproducing this")
w("")
w("```bash")
w("python scripts/audit_fullpanel.py --parquet   # convert + verify (~10 min, ~3 GB RAM)")
w("python scripts/audit_fullpanel.py --stats     # assignment + spectrogram checks")
w("python scripts/audit_fullpanel.py --seam      # segment-boundary analysis")
w("python scripts/mmx_label_resolver.py <csv> --out <json>   # §6 MMX identity")
w("python scripts/gen_fullpanel_doc.py           # regenerate this document")
w("```")
w("")
w("| Evidence file | Contents |")
w("|---|---|")
w("| `output/audit_fullpanel/parquet_verification.json` | §3 |")
w("| `output/audit_fullpanel/segment_seam.json` | §2 |")
w("| `output/audit_fullpanel/summary.json` | §4, §5 |")
w("| `output/audit_fullpanel/column_review_table.csv` | per-column table, all 4,103 columns |")
w("| `output/audit_fullpanel/mmx_label_match.json` | §6 — I-group → MMX instrument, by label reconstruction |")
w("")

DOC.parent.mkdir(parents=True, exist_ok=True)
DOC.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {DOC} ({len(L)} lines)")
